name: Integration Tests

on:
  workflow_dispatch:

env:
  FORCE_COLOR: 1
  TERM: xterm-color

jobs:
  test:
    name: Integration Tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install packages
        run: npm install

      - name: Retrieve configuration
        run: |
          # This expects yq from https://mikefarah.gitbook.io/yq, version 4.x
          yq -n '{
            "apiId": ${{ secrets.TDLIB_API_ID }},
            "apiHash": "${{ secrets.TDLIB_API_HASH }}"
          }' > integration-tests/credentials.yaml
          mkdir _td_database
          openssl enc -in integration-tests/td.binlog.aes -out _td_database/td.binlog -d -aes256 \
            -pass 'pass:${{ secrets.TDLIB_AES_KEY }}' -pbkdf2

      - name: Run tests
        run: npm run integration-tests
