name: Integration Tests

on:
  workflow_run:
    workflows:
      - Test and Deploy
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

concurrency: integration-tests

jobs:
  test:
    name: Integration Tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Setup node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install packages
        run: npm install

      - name: Retrieve configuration
        run: |
          # This expects yq from https://mikefarah.gitbook.io/yq, version 4.x
          yq -n '{
            "apiId": ${{ secrets.TDLIB_API_ID }},
            "apiHash": "${{ secrets.TDLIB_API_HASH }}",
            "aesKey": "${{ secrets.TDLIB_AES_KEY }}"
          }' > integration-tests/credentials.yaml

      - name: Run tests
        run: npm run integration-tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
