name: Integration Tests

on:
  workflow_dispatch:

env:
  FORCE_COLOR: 1
  TERM: xterm-color

jobs:
  test:
    name: Integration Tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install packages
        run: npm install

      - name: Retrieve configuration
        run: |
          cat <<< '${{ secrets.INTEGRATION_TESTS_CONFIG }}' > integration-tests/config.yaml
          mkdir _td_database
          openssl enc -in integration-tests/td.binlog.aes -out _td_database/td.binlog -d -aes256 -pass '${{ secrets.INTEGRATION_TESTS_AES_KEY }}' -pbkdf2

      - name: Run tests
        run: npm run integration-tests
