name: Integration Tests

on:
  workflow_dispatch:

env:
  FORCE_COLOR: 1
  TERM: xterm-color

jobs:
  test:
    name: Integration Tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install packages
        run: npm install

      - name: Retrieve secrets
        run: |
          cat <<< '${{ secrets.INTEGRATION_TESTS_CONFIG }}' > './integration-tests/config.yaml'
          cat './integration-tests/config.yaml'

      - name: Run tests
        run: npm run integration-tests
