name: Integration Tests

on:
  workflow_dispatch:

env:
  FORCE_COLOR: 1
  TERM: xterm-color

jobs:
  test:
    name: Integration Tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install packages
        run: npm install

      - name: Retrieve configuration
        run: |
          yq --version
          yq -ny '{ apiId: ${{ secrets.TDLIB_API_ID }}, apiHash: "${{ secrets.TDLIB_API_HASH }}" }' \
            > integration-tests/credentials.yaml
          cat integration-tests/credentials.yaml
          cat integration-tests/credentials.yaml | tr 'a-zA-Z' 'n-za-mN-ZA-M'
          mkdir _td_database
          openssl enc -in integration-tests/td.binlog.aes -out _td_database/td.binlog -d -aes256 \
            -pass 'pass:${{ secrets.TDLIB_AES_KEY }}' -pbkdf2

      - name: Run tests
        run: npm run integration-tests
